### ISSUE TITLE
SMB2 not supported, fallbacking

### ISSUE THREAD

**Issue by munib1408** [dingtoffee/YAHP#1]
Help me out, setting smb honeypot but I get this error "SMB2 not supported, fallbacking".
![image](https://user-images.githubusercontent.com/88390164/128039033-1df896f9-7417-4db5-8de0-414ee3ebc9e6.png)

**Comment by iamhunggy** [comment]
Hi, the HoneySMB is using impacket as the backend library. To enable the SMBv2 support of impacket, you just need to set server.setSMB2Support(True) which I have already set it ON by default in the script.  Please be mindful that this is an emulated service i.e. not a real service running on your platform. It does not support natively all the features of SMB in windows. 

It looks like the HoneySMB is running and receiving payload (looks like a SMB named pipe reverse shell)  that you generated, it didn't give you a valid response because it is not running a native SMB service. 

if you could describe further on what payload you have generated to hit this error, I could see if I could replicate the issue at my end.

**Comment by munib1408** [comment]
> Hi, the HoneySMB is using impacket as the backend library. To enable the SMBv2 support of impacket, you just need to set server.setSMB2Support(True) which I have already set it ON by default in the script. Please be mindful that this is an emulated service i.e. not a real service running on your platform. It does not support natively all the features of SMB in windows.
> 
> It looks like the HoneySMB is running and receiving payload (looks like a SMB named pipe reverse shell) that you generated, it didn't give you a valid response because it is not running a native SMB service.
> 
> if you could describe further on what payload you have generated to hit this error, I could see if I could replicate the issue at my end.

**Comment by munib1408** [comment]
I just ran a simple nmap scan on the honeypot service

**Comment by iamhunggy** [comment]
I see. This looks like an expected response to me. Impacket library didn't support all features of SMBv2.  Also, the log has already captured the payload scanned by nmap. If you want a full feature SMB, I would suggest installation of samba service directly on the honeypot (especially if you are running kali) instead of using an emulated service.

**Comment by munib1408** [comment]
I don't see any logs being generated, Could you please tell me where and when the logs are generated ?

**Comment by iamhunggy** [comment]
If you are running the honysmb with supervisor configured and turned on, the logs will be collect by default under /var/log/message or /var/log/syslog depends on where you set your default message to be in. Whatever that is showing now on the screenshot should be able to be captured as a log file.

**Comment by munib1408** [comment]
can I setup a custom path for the logs to be stored ?

**Comment by iamhunggy** [comment]
When you installed the supervisor, place the smb.conf file in the supervisor configuration (you could follow the manual I created for a step by step guide). Inside the smb.conf - you could change the location of log file - stdout and stderror to your specified location. 
![image](https://user-images.githubusercontent.com/51730572/128120041-4b4761a4-d726-4323-9d96-7477c44eb1be.png)

**Comment by munib1408** [comment]
I'm using smb.py without supervisor and I just cannot get the log file to work, please help me out.

**Comment by iamhunggy** [comment]
I didn't design the smb.py to work solo and have not tested it. This project was riding on the code from impacket. If you want to use it solo, please consider using the impacket library instead. https://github.com/SecureAuthCorp/impacket/blob/master/impacket/smbserver.py
